### ISSUE TITLE
`SES_IMPORT_REJECTED` upon importing viem

### ISSUE THREAD

**Issue by firnprotocol** [MetaMask/template-snap-monorepo#48]
hi all, SES is rejecting my import of [viem](https://viem.sh/), a simple and minimal ethereum library.

to reproduce: in this repo,
- navigate to `/packages/snap/`.
- run `yarn add viem`.
- add the line `import { keccak256 } from 'viem';` right here:
https://github.com/MetaMask/template-snap-monorepo/blob/c0d6591bcf30c2134544db0c88327f94553ffc34/packages/snap/src/index.ts#L2
- run `yarn start` in the top-level directory of the repo.

this will yield:
```
[SyntaxError: Possible import expression rejected at <unknown>:10280. (SES_IMPORT_REJECTED)]
Error during initial build. Error: Snap evaluation error: Process exited with non-zero exit code: 255
    at evalHandler (/Users/firnprotocol/template-snap-monorepo/node_modules/@metamask/snaps-cli/dist/cmds/eval/evalHandler.js:21:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildSnap (/Users/firnprotocol/template-snap-monorepo/node_modules/@metamask/snaps-cli/dist/cmds/watch/watchHandler.js:47:17)
```

this is obviously not acceptable for even the simplest snaps.

thanks in advance for your attention.

**Comment by firnprotocol** [comment]
re-raised here: https://github.com/MetaMask/snaps/issues/1443.
