### ISSUE TITLE
`yarn start` fails on Windows 10

### ISSUE THREAD

**Issue by Montoya** [MetaMask/template-snap-monorepo#64]
Attempting to run the template on Windows 10 with `yarn && yarn start` produces the following error for the snap package: 

```
➤ YN0000: [snap]: Process started
➤ YN0000: [snap]: - Checking the input file.
➤ YN0000: [snap]: - Starting the development server.
➤ YN0000: [snap]: ℹ The server is listening on http://localhost:8080.
➤ YN0000: [snap]: - Building the snap bundle.
➤ YN0000: [snap]: C:\Users\sirok\Documents\GitRepos\pet-fox-v2\node_modules\@metamask\snaps-cli\dist\cjs\webpack\plugins.js:215
➤ YN0000: [snap]:             if ((0, _module.isBuiltin)(baseRequest) && !this.options.ignore?.includes(baseRequest)) {
➤ YN0000: [snap]:                                       ^
➤ YN0000: [snap]:
➤ YN0000: [snap]: TypeError: (0 , _module.isBuiltin) is not a function
➤ YN0000: [snap]:     at C:\Users\sirok\Documents\GitRepos\pet-fox-v2\node_modules\@metamask\snaps-cli\dist\cjs\webpack\plugins.js:215:39
➤ YN0000: [snap]:     at Hook.eval [as callAsync] (eval at create (C:\Users\sirok\Documents\GitRepos\pet-fox-v2\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:37:1)
➤ YN0000: [snap]:     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\sirok\Documents\GitRepos\pet-fox-v2\node_modules\tapable\lib\Hook.js:18:14)
➤ YN0000: [snap]:     at Resolver.doResolve (C:\Users\sirok\Documents\GitRepos\pet-fox-v2\node_modules\enhanced-resolve\lib\Resolver.js:516:16)
➤ YN0000: [snap]:     at C:\Users\sirok\Documents\GitRepos\pet-fox-v2\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:76:17
➤ YN0000: [snap]:     at C:\Users\sirok\Documents\GitRepos\pet-fox-v2\node_modules\enhanced-resolve\lib\DescriptionFileUtils.js:145:13
➤ YN0000: [snap]:     at C:\Users\sirok\Documents\GitRepos\pet-fox-v2\node_modules\enhanced-resolve\lib\forEachBail.js:39:13
➤ YN0000: [snap]:     at onJson (C:\Users\sirok\Documents\GitRepos\pet-fox-v2\node_modules\enhanced-resolve\lib\DescriptionFileUtils.js:130:6)
➤ YN0000: [snap]:     at C:\Users\sirok\Documents\GitRepos\pet-fox-v2\node_modules\enhanced-resolve\lib\DescriptionFileUtils.js:83:7
➤ YN0000: [snap]:     at processTicksAndRejections (node:internal/process/task_queues:83:21)
➤ YN0000: [snap]: Process exited (exit code 1), completed in 3s 362ms
```

**Comment by Mrtenz** [comment]
This is due to a Node.js incompatibility. The latest version of the Snaps CLI should properly check if your current Node.js version is supported.
